name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.0'
          channel: 'stable'

      - name: Flutter Upgrade
        run: flutter upgrade

      - name: Install dependencies
        run: flutter pub get

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: |
          curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/

      - name: Build and analyze SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: $HOME/.sonar/sonar-scanner-6.2.1.4610-linux-x64/bin/sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization_key
          
      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
